.TH "Array.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Array.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br
\fC#include 'ReferenceCountedArray.h'\fP
.br
\fC#include 'String.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArray< T >\fP"
.br
.RI "\fIDynamic \fBArray\fP. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_W_ARRAY_H\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _W_ARRAY_H   1"
.PP
Definition at line 24 of file Array.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
