.TH "Base64" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base64 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <base64.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 31 of file base64.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
