.TH "bdlib.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bdlib.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bits.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_BDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBBDLIB_NS\fP   bd"
.br
.ti -1c
.RI "#define \fBBDLIB_NS_BEGIN\fP   namespace bd {"
.br
.ti -1c
.RI "#define \fBBDLIB_NS_END\fP   }"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_BDLIB_H   1"
.PP
Definition at line 24 of file bdlib.h.
.SS "#define BDLIB_NS   bd"
.PP
Definition at line 43 of file bdlib.h.
.SS "#define BDLIB_NS_BEGIN   namespace bd {"
.PP
Definition at line 41 of file bdlib.h.
.SS "#define BDLIB_NS_END   }"
.PP
Definition at line 42 of file bdlib.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
