.TH "BinaryTree" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryTree \- Binary tree data structure.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <BinaryTree.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class Key, class Value> class BinaryTree< Key, Value >"
Binary tree data structure. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
