.TH "bits.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bits.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBIT0\fP   (uint32_t) 0x000000001"
.br
.ti -1c
.RI "#define \fBBIT1\fP   (uint32_t) 0x000000002"
.br
.ti -1c
.RI "#define \fBBIT10\fP   (uint32_t) 0x000000400"
.br
.ti -1c
.RI "#define \fBBIT11\fP   (uint32_t) 0x000000800"
.br
.ti -1c
.RI "#define \fBBIT12\fP   (uint32_t) 0x000001000"
.br
.ti -1c
.RI "#define \fBBIT13\fP   (uint32_t) 0x000002000"
.br
.ti -1c
.RI "#define \fBBIT14\fP   (uint32_t) 0x000004000"
.br
.ti -1c
.RI "#define \fBBIT15\fP   (uint32_t) 0x000008000"
.br
.ti -1c
.RI "#define \fBBIT16\fP   (uint32_t) 0x000010000"
.br
.ti -1c
.RI "#define \fBBIT17\fP   (uint32_t) 0x000020000"
.br
.ti -1c
.RI "#define \fBBIT18\fP   (uint32_t) 0x000040000"
.br
.ti -1c
.RI "#define \fBBIT19\fP   (uint32_t) 0x000080000"
.br
.ti -1c
.RI "#define \fBBIT2\fP   (uint32_t) 0x000000004"
.br
.ti -1c
.RI "#define \fBBIT20\fP   (uint32_t) 0x000100000"
.br
.ti -1c
.RI "#define \fBBIT21\fP   (uint32_t) 0x000200000"
.br
.ti -1c
.RI "#define \fBBIT22\fP   (uint32_t) 0x000400000"
.br
.ti -1c
.RI "#define \fBBIT23\fP   (uint32_t) 0x000800000"
.br
.ti -1c
.RI "#define \fBBIT24\fP   (uint32_t) 0x001000000"
.br
.ti -1c
.RI "#define \fBBIT25\fP   (uint32_t) 0x002000000"
.br
.ti -1c
.RI "#define \fBBIT26\fP   (uint32_t) 0x004000000"
.br
.ti -1c
.RI "#define \fBBIT27\fP   (uint32_t) 0x008000000"
.br
.ti -1c
.RI "#define \fBBIT28\fP   (uint32_t) 0x010000000"
.br
.ti -1c
.RI "#define \fBBIT29\fP   (uint32_t) 0x020000000"
.br
.ti -1c
.RI "#define \fBBIT3\fP   (uint32_t) 0x000000008"
.br
.ti -1c
.RI "#define \fBBIT30\fP   (uint32_t) 0x040000000"
.br
.ti -1c
.RI "#define \fBBIT31\fP   (uint32_t) 0x080000000"
.br
.ti -1c
.RI "#define \fBBIT4\fP   (uint32_t) 0x000000010"
.br
.ti -1c
.RI "#define \fBBIT5\fP   (uint32_t) 0x000000020"
.br
.ti -1c
.RI "#define \fBBIT6\fP   (uint32_t) 0x000000040"
.br
.ti -1c
.RI "#define \fBBIT7\fP   (uint32_t) 0x000000080"
.br
.ti -1c
.RI "#define \fBBIT8\fP   (uint32_t) 0x000000100"
.br
.ti -1c
.RI "#define \fBBIT9\fP   (uint32_t) 0x000000200"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BIT0   (uint32_t) 0x000000001"
.PP
Definition at line 1 of file bits.h.
.SS "#define BIT1   (uint32_t) 0x000000002"
.PP
Definition at line 2 of file bits.h.
.SS "#define BIT10   (uint32_t) 0x000000400"
.PP
Definition at line 11 of file bits.h.
.SS "#define BIT11   (uint32_t) 0x000000800"
.PP
Definition at line 12 of file bits.h.
.SS "#define BIT12   (uint32_t) 0x000001000"
.PP
Definition at line 13 of file bits.h.
.SS "#define BIT13   (uint32_t) 0x000002000"
.PP
Definition at line 14 of file bits.h.
.SS "#define BIT14   (uint32_t) 0x000004000"
.PP
Definition at line 15 of file bits.h.
.SS "#define BIT15   (uint32_t) 0x000008000"
.PP
Definition at line 16 of file bits.h.
.SS "#define BIT16   (uint32_t) 0x000010000"
.PP
Definition at line 17 of file bits.h.
.SS "#define BIT17   (uint32_t) 0x000020000"
.PP
Definition at line 18 of file bits.h.
.SS "#define BIT18   (uint32_t) 0x000040000"
.PP
Definition at line 19 of file bits.h.
.SS "#define BIT19   (uint32_t) 0x000080000"
.PP
Definition at line 20 of file bits.h.
.SS "#define BIT2   (uint32_t) 0x000000004"
.PP
Definition at line 3 of file bits.h.
.SS "#define BIT20   (uint32_t) 0x000100000"
.PP
Definition at line 21 of file bits.h.
.SS "#define BIT21   (uint32_t) 0x000200000"
.PP
Definition at line 22 of file bits.h.
.SS "#define BIT22   (uint32_t) 0x000400000"
.PP
Definition at line 23 of file bits.h.
.SS "#define BIT23   (uint32_t) 0x000800000"
.PP
Definition at line 24 of file bits.h.
.SS "#define BIT24   (uint32_t) 0x001000000"
.PP
Definition at line 25 of file bits.h.
.SS "#define BIT25   (uint32_t) 0x002000000"
.PP
Definition at line 26 of file bits.h.
.SS "#define BIT26   (uint32_t) 0x004000000"
.PP
Definition at line 27 of file bits.h.
.SS "#define BIT27   (uint32_t) 0x008000000"
.PP
Definition at line 28 of file bits.h.
.SS "#define BIT28   (uint32_t) 0x010000000"
.PP
Definition at line 29 of file bits.h.
.SS "#define BIT29   (uint32_t) 0x020000000"
.PP
Definition at line 30 of file bits.h.
.SS "#define BIT3   (uint32_t) 0x000000008"
.PP
Definition at line 4 of file bits.h.
.SS "#define BIT30   (uint32_t) 0x040000000"
.PP
Definition at line 31 of file bits.h.
.SS "#define BIT31   (uint32_t) 0x080000000"
.PP
Definition at line 32 of file bits.h.
.SS "#define BIT4   (uint32_t) 0x000000010"
.PP
Definition at line 5 of file bits.h.
.SS "#define BIT5   (uint32_t) 0x000000020"
.PP
Definition at line 6 of file bits.h.
.SS "#define BIT6   (uint32_t) 0x000000040"
.PP
Definition at line 7 of file bits.h.
.SS "#define BIT7   (uint32_t) 0x000000080"
.PP
Definition at line 8 of file bits.h.
.SS "#define BIT8   (uint32_t) 0x000000100"
.PP
Definition at line 9 of file bits.h.
.SS "#define BIT9   (uint32_t) 0x000000200"
.PP
Definition at line 10 of file bits.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
