.TH "Crypto" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crypto \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Crypto.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrypto\fP (const \fBCrypto\fP &crypter)"
.br
.ti -1c
.RI "\fBCrypto\fP (const unsigned char *key, const unsigned char *iv=NULL)"
.br
.ti -1c
.RI "\fB~Crypto\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file Crypto.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Crypto::Crypto (const unsigned char * key, const unsigned char * iv = \fCNULL\fP)"
.PP
.SS "Crypto::Crypto (const \fBCrypto\fP & crypter)\fC [inline]\fP"
.PP
Definition at line 40 of file Crypto.h.
.SS "Crypto::~Crypto ()\fC [inline]\fP"
.PP
Definition at line 41 of file Crypto.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
