.TH "Cstrings.c" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cstrings.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Cstrings.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBcalloc\fP (size_t nmemb, size_t size)"
.br
.ti -1c
.RI "void * \fBrealloc\fP (void *ptr, size_t size)"
.br
.ti -1c
.RI "void \fBstr_redup\fP (char **str, const char *newstr)"
.br
.ti -1c
.RI "char * \fBstrdup\fP (const char *entry)"
.br
.ti -1c
.RI "size_t \fBstrlcat\fP (char *dst, const char *src, size_t siz)"
.br
.ti -1c
.RI "BDLIB_NS_BEGIN size_t \fBstrlcpy\fP (char *dst, const char *src, size_t siz)"
.br
.ti -1c
.RI "char * \fBstrldup\fP (const char *entry, size_t maxlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* calloc (size_t nmemb, size_t size)"
.PP
Definition at line 128 of file Cstrings.c.
.SS "void* realloc (void * ptr, size_t size)"
.PP
Definition at line 138 of file Cstrings.c.
.SS "void str_redup (char ** str, const char * newstr)"
.PP
Definition at line 93 of file Cstrings.c.
.SS "char* strdup (const char * entry)"
.PP
Definition at line 108 of file Cstrings.c.
.SS "size_t strlcat (char * dst, const char * src, size_t siz)"
.PP
Definition at line 65 of file Cstrings.c.
.SS "BDLIB_NS_BEGIN size_t strlcpy (char * dst, const char * src, size_t siz)"
.PP
Definition at line 34 of file Cstrings.c.
.SS "char* strldup (const char * entry, size_t maxlen)"
.PP
Definition at line 118 of file Cstrings.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
