.TH "Cstrings.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cstrings.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_CSTRINGS_H\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBcalloc\fP (size_t, size_t)"
.br
.ti -1c
.RI "void * \fBrealloc\fP (void *, size_t)"
.br
.ti -1c
.RI "void \fBstr_redup\fP (char **, const char *)"
.br
.ti -1c
.RI "char * \fBstrdup\fP (const char *)"
.br
.ti -1c
.RI "size_t \fBstrlcat\fP (char *, const char *, size_t)"
.br
.ti -1c
.RI "BDLIB_NS_BEGIN size_t \fBstrlcpy\fP (char *, const char *, size_t)"
.br
.ti -1c
.RI "char * \fBstrldup\fP (const char *, size_t)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_CSTRINGS_H   1"
.PP
Definition at line 24 of file Cstrings.h.
.SH "Function Documentation"
.PP 
.SS "void* calloc (size_t, size_t)"
.PP
Definition at line 128 of file Cstrings.c.
.SS "void* realloc (void *, size_t)"
.PP
Definition at line 138 of file Cstrings.c.
.SS "void str_redup (char **, const char *)"
.PP
Definition at line 93 of file Cstrings.c.
.SS "char* strdup (const char *)"
.PP
Definition at line 108 of file Cstrings.c.
.SS "size_t strlcat (char *, const char *, size_t)"
.PP
Definition at line 65 of file Cstrings.c.
.SS "BDLIB_NS_BEGIN size_t strlcpy (char *, const char *, size_t)"
.PP
Definition at line 34 of file Cstrings.c.
.SS "char* strldup (const char *, size_t)"
.PP
Definition at line 118 of file Cstrings.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
