.TH "hash.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br
\fC#include <sys/types.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhash< T * >\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_HASH_H\fP   1"
.br
.ti -1c
.RI "#define \fBtr1_hashtable_define_trivial_hash\fP(T)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (long)"
.br
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (int)"
.br
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (short)"
.br
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (unsigned char)"
.br
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (signed char)"
.br
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (char)"
.br
.ti -1c
.RI "\fBtr1_hashtable_define_trivial_hash\fP (bool)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_HASH_H   1"
.PP
Definition at line 32 of file hash.h.
.SS "#define tr1_hashtable_define_trivial_hash(T)"
.PP
\fBValue:\fP
.PP
.nf
template<>                                                                        \
  struct hash<T>                                                                  \
  {                                                                               \
    inline size_t operator()(T val) const { return static_cast<size_t>(val); }    \
  }
.fi
.PP
Definition at line 42 of file hash.h.
.SH "Function Documentation"
.PP 
.SS "tr1_hashtable_define_trivial_hash (long)"
.PP
.SS "tr1_hashtable_define_trivial_hash (int)"
.PP
.SS "tr1_hashtable_define_trivial_hash (short)"
.PP
.SS "tr1_hashtable_define_trivial_hash (unsigned char)"
.PP
.SS "tr1_hashtable_define_trivial_hash (signed char)"
.PP
.SS "tr1_hashtable_define_trivial_hash (char)"
.PP
.SS "tr1_hashtable_define_trivial_hash (bool)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
