.TH "hash< String >" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash< String > \- 
.SH SYNOPSIS
.br
.PP
\fC#include <String.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const \fBString\fP &val) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct hash< String >"

.PP
Definition at line 287 of file String.h.
.SH "Member Function Documentation"
.PP 
.SS "size_t hash< \fBString\fP >::operator() (const \fBString\fP & val) const\fC [inline]\fP"
.PP
Definition at line 289 of file String.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
