.TH "hash< T * >" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash< T * > \- 
.SH SYNOPSIS
.br
.PP
\fC#include <hash.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (T *p) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> struct hash< T * >"
TODO: float double long double char * const char * \fBString\fP 
.PP
Definition at line 73 of file hash.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
