.TH "HashTable" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashTable \- \fBHashTable\fP data structure.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <HashTable.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class Key, class Value> class HashTable< Key, Value >"
\fBHashTable\fP data structure. 

\fBTodo\fP
.RS 4
replace() 
.PP
iterators 
.PP
resizing/growing
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
