.TH "KeyValue" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyValue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Iterator.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const Key & \fBkey\fP () const "
.br
.ti -1c
.RI "\fBKeyValue\fP (const \fBKeyValue\fP &kv)"
.br
.ti -1c
.RI "\fBKeyValue\fP (const Key &_key, const Value &_value)"
.br
.ti -1c
.RI "\fBKeyValue\fP ()"
.br
.ti -1c
.RI "const Value & \fBvalue\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Key \fBk\fP"
.br
.ti -1c
.RI "Value \fBv\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBKeyValue\fP &lhs, const \fBKeyValue\fP &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Key, class Value> struct KeyValue< Key, Value >"

.PP
Definition at line 84 of file Iterator.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Key , class Value > \fBKeyValue\fP< Key, Value >::\fBKeyValue\fP ()\fC [inline]\fP"
.PP
Definition at line 89 of file Iterator.h.
.SS "template<class Key , class Value > \fBKeyValue\fP< Key, Value >::\fBKeyValue\fP (const Key & _key, const Value & _value)\fC [inline]\fP"
.PP
Definition at line 90 of file Iterator.h.
.SS "template<class Key , class Value > \fBKeyValue\fP< Key, Value >::\fBKeyValue\fP (const \fBKeyValue\fP< Key, Value > & kv)\fC [inline]\fP"
.PP
Definition at line 91 of file Iterator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Key , class Value > const Key& \fBKeyValue\fP< Key, Value >::key () const\fC [inline]\fP"
.PP
Definition at line 93 of file Iterator.h.
.SS "template<class Key , class Value > const Value& \fBKeyValue\fP< Key, Value >::value () const\fC [inline]\fP"
.PP
Definition at line 94 of file Iterator.h.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class Key , class Value > bool operator== (const \fBKeyValue\fP< Key, Value > & lhs, const \fBKeyValue\fP< Key, Value > & rhs)\fC [friend]\fP"
.PP
Definition at line 97 of file Iterator.h.
.SH "Member Data Documentation"
.PP 
.SS "template<class Key , class Value > Key \fBKeyValue\fP< Key, Value >::\fBk\fP"
.PP
Definition at line 86 of file Iterator.h.
.SS "template<class Key , class Value > Value \fBKeyValue\fP< Key, Value >::\fBv\fP"
.PP
Definition at line 87 of file Iterator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
