.TH "List::Node" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List::Node \- 
.SH SYNOPSIS
.br
.PP
\fC#include <List.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (const \fBiterator_type\fP &p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBiterator_type\fP \fBptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> struct List< T >::Node"

.PP
Definition at line 44 of file List.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBList\fP< T >::List::Node::Node (const \fBiterator_type\fP & p)\fC [inline]\fP"
.PP
Definition at line 49 of file List.h.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> \fBNode\fP* \fBList\fP< T >::\fBList::Node::next\fP"
.PP
Definition at line 46 of file List.h.
.SS "template<class T> \fBNode\fP* \fBList\fP< T >::\fBList::Node::prev\fP"
.PP
Definition at line 47 of file List.h.
.SS "template<class T> \fBiterator_type\fP \fBList\fP< T >::\fBList::Node::ptr\fP"
.PP
Definition at line 45 of file List.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
