.TH "List.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br
\fC#include 'Iterator.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBList< T >\fP"
.br
.RI "\fI\fBList\fP data structure. \fP"
.ti -1c
.RI "class \fBList< T >::List::ListIterator\fP"
.br
.ti -1c
.RI "struct \fBList< T >::List::Node\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_LIST_H\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_LIST_H   1"
.PP
Definition at line 24 of file List.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
