.TH "Queue.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queue.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iterator>\fP
.br
\fC#include 'bdlib.h'\fP
.br
\fC#include 'List.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQueue< T >\fP"
.br
.RI "\fIA FIFO \fBQueue\fP, what else! \fP"
.ti -1c
.RI "class \fBQueueConstIterator< T >\fP"
.br
.ti -1c
.RI "class \fBQueueIterator< T >\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_QUEUE_H\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_QUEUE_H   1"
.PP
Definition at line 24 of file Queue.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
