.TH "QueueIterator" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueIterator \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Queue.h>\fP
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBQueueConstIterator\fP< T > \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBQueueIterator\fP< T > \fBiterator\fP"
.br
.ti -1c
.RI "typedef std::forward_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef Queue_t::Node \fBNode\fP"
.br
.ti -1c
.RI "typedef T * \fBpointer\fP"
.br
.ti -1c
.RI "typedef \fBQueue\fP< T > \fBQueue_t\fP"
.br
.ti -1c
.RI "typedef T & \fBreference\fP"
.br
.ti -1c
.RI "typedef size_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &iter) const "
.br
.ti -1c
.RI "\fBreference\fP \fBoperator*\fP () const "
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBpointer\fP \fBoperator->\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &iter) const "
.br
.ti -1c
.RI "\fBQueueIterator\fP ()"
.br
.ti -1c
.RI "\fB~QueueIterator\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQueue< T >\fP"
.br
.ti -1c
.RI "class \fBQueueConstIterator< T >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class QueueIterator< T >"

.PP
Definition at line 111 of file Queue.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T > typedef \fBQueueConstIterator\fP<T> \fBQueueIterator\fP< T >::\fBconst_iterator\fP"
.PP
Definition at line 118 of file Queue.h.
.SS "template<class T > typedef ptrdiff_t \fBQueueIterator\fP< T >::\fBdifference_type\fP"
.PP
Definition at line 122 of file Queue.h.
.SS "template<class T > typedef \fBQueueIterator\fP<T> \fBQueueIterator\fP< T >::\fBiterator\fP"
.PP
Definition at line 117 of file Queue.h.
.SS "template<class T > typedef std::forward_iterator_tag \fBQueueIterator\fP< T >::\fBiterator_category\fP"
.PP
Definition at line 120 of file Queue.h.
.SS "template<class T > typedef Queue_t::Node \fBQueueIterator\fP< T >::\fBNode\fP"
.PP
Definition at line 119 of file Queue.h.
.SS "template<class T > typedef T* \fBQueueIterator\fP< T >::\fBpointer\fP"
.PP
Definition at line 125 of file Queue.h.
.SS "template<class T > typedef \fBQueue\fP<T> \fBQueueIterator\fP< T >::\fBQueue_t\fP"
.PP
Definition at line 116 of file Queue.h.
.SS "template<class T > typedef T& \fBQueueIterator\fP< T >::\fBreference\fP"
.PP
Definition at line 124 of file Queue.h.
.SS "template<class T > typedef size_t \fBQueueIterator\fP< T >::\fBsize_type\fP"
.PP
Definition at line 123 of file Queue.h.
.SS "template<class T > typedef T \fBQueueIterator\fP< T >::\fBvalue_type\fP"
.PP
Definition at line 121 of file Queue.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBQueueIterator\fP< T >::\fBQueueIterator\fP ()\fC [inline]\fP"
.PP
Definition at line 133 of file Queue.h.
.SS "template<class T > \fBQueueIterator\fP< T >::~\fBQueueIterator\fP ()\fC [inline]\fP"
.PP
Definition at line 134 of file Queue.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > bool \fBQueueIterator\fP< T >::operator!= (const \fBiterator\fP & iter) const\fC [inline]\fP"
.PP
Definition at line 141 of file Queue.h.
.SS "template<class T > \fBreference\fP \fBQueueIterator\fP< T >::operator* () const\fC [inline]\fP"
.PP
Definition at line 136 of file Queue.h.
.SS "template<class T > \fBiterator\fP& \fBQueueIterator\fP< T >::operator++ ()\fC [inline]\fP"
.PP
Definition at line 150 of file Queue.h.
.SS "template<class T > \fBiterator\fP \fBQueueIterator\fP< T >::operator++ (int)\fC [inline]\fP"
.PP
Definition at line 144 of file Queue.h.
.SS "template<class T > \fBpointer\fP \fBQueueIterator\fP< T >::operator-> () const\fC [inline]\fP"
.PP
Definition at line 137 of file Queue.h.
.SS "template<class T > bool \fBQueueIterator\fP< T >::operator== (const \fBiterator\fP & iter) const\fC [inline]\fP"
.PP
Definition at line 140 of file Queue.h.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T > friend class \fBQueue\fP< T >\fC [friend]\fP"
.PP
Definition at line 112 of file Queue.h.
.SS "template<class T > friend class \fBQueueConstIterator\fP< T >\fC [friend]\fP"
.PP
Definition at line 113 of file Queue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
