.TH "ReferenceCountedArray.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReferenceCountedArray.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <stdint.h>\fP
.br
\fC#include <sys/types.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArrayRef< T >\fP"
.br
.RI "\fIHelps the \fBString\fP class with reference counting. \fP"
.ti -1c
.RI "class \fBReferenceCountedArray< T >\fP"
.br
.ti -1c
.RI "class \fBReferenceCountedArray< T >::ReferenceCountedArray::Cref\fP"
.br
.RI "\fISafe element reading and writing. \fP"
.ti -1c
.RI "class \fBSlice< T >\fP"
.br
.RI "\fISafe subarray reading and writing. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_W_REFERENCE_COUNTED_ARRAY_H\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _W_REFERENCE_COUNTED_ARRAY_H   1"
.PP
Definition at line 23 of file ReferenceCountedArray.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
