.TH "Slice" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Slice \- Safe subarray reading and writing.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ReferenceCountedArray.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator T\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP & \fBoperator=\fP (const T &array)"
.br
.ti -1c
.RI "\fBSlice\fP & \fBoperator=\fP (const \fBSlice\fP &slice)"
.br
.ti -1c
.RI "\fBSlice\fP (const \fBSlice\fP &slice)"
.br
.ti -1c
.RI "\fBSlice\fP (T &_rca, int _start, int _len)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class Slice< T >"
Safe subarray reading and writing. 

\fBTodo\fP
.RS 4
This should not provide copy constructors for Cref, they shouldn't be needed because of const char String::operator[] This class should be optimized away and fully inlined such that: \fBString\fP s('look over there'); s(0, 4) = 'blah''; Should be rewritten as: s.replace(0, 'blah', 4); 
.RE
.PP

.PP
Definition at line 122 of file ReferenceCountedArray.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > \fBSlice\fP& \fBSlice\fP< T >::operator= (const T & array)\fC [inline]\fP"
.PP
\fBTodo\fP
.RS 4
This needs to account for negative start/len 
.RE
.PP

.PP
Definition at line 152 of file ReferenceCountedArray.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
