.TH "Socket.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Socket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClientSocket\fP"
.br
.ti -1c
.RI "class \fBServerSocket\fP"
.br
.ti -1c
.RI "class \fBSocket\fP"
.br
.RI "\fI\fBSocket\fP class. \fP"
.ti -1c
.RI "struct \fBsockname_t\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_SOCKET_H\fP   1"
.br
.ti -1c
.RI "#define \fBSOCKET_ASYNC\fP   BIT3"
.br
.ti -1c
.RI "#define \fBSOCKET_BIND\fP   BIT2"
.br
.ti -1c
.RI "#define \fBSOCKET_CLIENT\fP   BIT0"
.br
.ti -1c
.RI "#define \fBSOCKET_SERVER\fP   BIT1"
.br
.ti -1c
.RI "#define \fBSOCKET_TCP\fP   BIT4"
.br
.ti -1c
.RI "#define \fBSOCKET_UDP\fP   BIT5"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_SOCKET_H   1"
.PP
Definition at line 24 of file Socket.h.
.SS "#define SOCKET_ASYNC   BIT3"
.PP
Definition at line 43 of file Socket.h.
.SS "#define SOCKET_BIND   BIT2"
.PP
Definition at line 42 of file Socket.h.
.SS "#define SOCKET_CLIENT   BIT0"
.PP
Definition at line 40 of file Socket.h.
.SS "#define SOCKET_SERVER   BIT1"
.PP
Definition at line 41 of file Socket.h.
.SS "#define SOCKET_TCP   BIT4"
.PP
Definition at line 44 of file Socket.h.
.SS "#define SOCKET_UDP   BIT5"
.PP
Definition at line 45 of file Socket.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
