.TH "sockname_t" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockname_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Socket.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct sockaddr \fBaddr\fP"
.br
.ti -1c
.RI "   struct sockaddr_in \fBipv4\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file Socket.h.
.SH "Member Data Documentation"
.PP 
.SS "struct sockaddr \fBsockname_t::addr\fP\fC [read]\fP"
.PP
Definition at line 51 of file Socket.h.
.SS "int \fBsockname_t::family\fP"
.PP
Definition at line 49 of file Socket.h.
.SS "struct sockaddr_in \fBsockname_t::ipv4\fP\fC [read]\fP"
.PP
Definition at line 52 of file Socket.h.
.SS "int \fBsockname_t::len\fP"
.PP
Definition at line 48 of file Socket.h.
.SS "union { ... }   \fBsockname_t::u\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
