.TH "Socket" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Socket \- \fBSocket\fP class.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <Socket.h>\fP
.PP
Inherited by ClientSocket, and ServerSocket.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocket\fP (int f)"
.br
.ti -1c
.RI "\fBSocket\fP (\fBSocket\fP &s)"
.br
.ti -1c
.RI "bool \fBcreate\fP ()"
.br
.ti -1c
.RI "bool \fBconnect\fP (const \fBString\fP host, const in_port_t port)"
.br
.ti -1c
.RI "bool \fBbind\fP (const in_port_t port)"
.br
.ti -1c
.RI "bool \fBlisten\fP () const "
.br
.ti -1c
.RI "bool \fBaccept\fP (\fBSocket\fP &) const "
.br
.ti -1c
.RI "bool \fBsend\fP (const \fBString\fP) const "
.br
.ti -1c
.RI "bool \fBrecv\fP (\fBString\fP &) const "
.br
.ti -1c
.RI "int \fBsetNonBlocking\fP (bool=1)"
.br
.ti -1c
.RI "bool \fBisValid\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSocket\fP class. 
.PP
Definition at line 65 of file Socket.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
