.TH "SortedList" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SortedList \- A \fBList\fP which sorts on insert.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <SortedList.h>\fP
.PP
Inherits \fBList< T >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ListIterator \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBcontains\fP (const iterator_type &ptr) const"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "const iterator_type \fBfind\fP (const iterator_type &ptr) const"
.br
.ti -1c
.RI "iterator_type & \fBfindRef\fP (const iterator_type &ptr)"
.br
.RI "\fIReturn a reference to the found element. \fP"
.ti -1c
.RI "virtual void \fBinsert\fP (const iterator_type &ptr)"
.br
.RI "\fIInsert an element into the list (ordered). \fP"
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "bool \fBremove\fP (const iterator_type &ptr)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "\fBSortedList\fP ()"
.br
.ti -1c
.RI "virtual \fB~SortedList\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBdeleteNode\fP (\fBNode\fP *node)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBhead\fP"
.br
.ti -1c
.RI "size_t \fBmy_size\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBtail\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBList\fP< iterator_type > & \fBoperator<<\fP (\fBList\fP< iterator_type > &list, const iterator_type &item)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class SortedList< T >"
A \fBList\fP which sorts on insert. 
.PP
Definition at line 36 of file SortedList.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef ListIterator \fBList\fP< T  >::\fBiterator\fP\fC [inherited]\fP"
.PP
Reimplemented in \fBQueue< T >\fP.
.PP
Definition at line 36 of file List.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBSortedList\fP< T >::\fBSortedList\fP ()\fC [inline]\fP"
.PP
Definition at line 41 of file SortedList.h.
.SS "template<class T > virtual \fBSortedList\fP< T >::~\fBSortedList\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 42 of file SortedList.h.
.SH "Member Function Documentation"
.PP 
.SS "\fBiterator\fP \fBList\fP< T  >::begin ()\fC [inline, inherited]\fP"
.PP
Reimplemented in \fBQueue< T >\fP.
.PP
Definition at line 251 of file List.h.
.SS "void \fBList\fP< T  >::clear ()\fC [inline, inherited]\fP"
.PP
Definition at line 89 of file List.h.
.SS "bool \fBList\fP< T  >::contains (const \fBiterator_type\fP & ptr) const\fC [inline, inherited]\fP"
.PP
Definition at line 128 of file List.h.
.SS "void \fBList\fP< T  >::deleteNode (Node * node)\fC [inline, protected, inherited]\fP"
.PP
Definition at line 52 of file List.h.
.SS "\fBiterator\fP \fBList\fP< T  >::end ()\fC [inline, inherited]\fP"
.PP
Reimplemented in \fBQueue< T >\fP.
.PP
Definition at line 252 of file List.h.
.SS "const iterator_type \fBList\fP< T  >::find (const \fBiterator_type\fP & ptr) const\fC [inline, inherited]\fP"
.PP
Definition at line 138 of file List.h.
.SS "iterator_type& \fBList\fP< T  >::findRef (const \fBiterator_type\fP & ptr)\fC [inline, inherited]\fP"
.PP
Return a reference to the found element. 
.PP
Definition at line 152 of file List.h.
.SS "template<class T > virtual void \fBSortedList\fP< T >::insert (const iterator_type & ptr)\fC [inline, virtual]\fP"
.PP
Insert an element into the list (ordered). 
.PP
\fBParameters:\fP
.RS 4
\fIptr\fP The element to insert This operation is O(n/2) 
.RE
.PP

.PP
Reimplemented from \fBList< T >\fP.
.PP
Definition at line 49 of file SortedList.h.
.SS "bool \fBList\fP< T  >::isEmpty () const\fC [inline, inherited]\fP"
.PP
Definition at line 101 of file List.h.
.SS "bool \fBList\fP< T  >::remove (const \fBiterator_type\fP & ptr)\fC [inline, inherited]\fP"
.PP
Definition at line 161 of file List.h.
.SS "size_t \fBList\fP< T  >::size () const\fC [inline, inherited]\fP"
.PP
Definition at line 100 of file List.h.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBList\fP<iterator_type>& operator<< (\fBList\fP< \fBiterator_type\fP > & list, const \fBiterator_type\fP & item)\fC [friend, inherited]\fP"
.PP
\fBSee also:\fP
.RS 4
\fBinsert\fP 
.RE
.PP

.PP
Definition at line 123 of file List.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* \fBList\fP< T  >::\fBhead\fP\fC [protected, inherited]\fP"
.PP
Definition at line 67 of file List.h.
.SS "size_t \fBList\fP< T  >::\fBmy_size\fP\fC [protected, inherited]\fP"
.PP
Definition at line 69 of file List.h.
.SS "\fBNode\fP* \fBList\fP< T  >::\fBtail\fP\fC [protected, inherited]\fP"
.PP
Definition at line 68 of file List.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
