.TH "SortedList" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SortedList \- A \fBList\fP which sorts on insert.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <SortedList.h>\fP
.PP
Inherits \fBList< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinsert\fP (const iterator_type &ptr)"
.br
.RI "\fIInsert an element into the list (ordered). \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class SortedList< T >"
A \fBList\fP which sorts on insert. 
.PP
Definition at line 37 of file SortedList.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > virtual void \fBSortedList\fP< T >::insert (const iterator_type & ptr)\fC [inline, virtual]\fP"
.PP
Insert an element into the list (ordered). 
.PP
\fBParameters:\fP
.RS 4
\fIptr\fP The element to insert This operation is O(n/2) 
.RE
.PP

.PP
Reimplemented from \fBList< T >\fP.
.PP
Definition at line 50 of file SortedList.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
