.TH "Stack" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stack \- A FILO \fBStack\fP, what else!  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <Stack.h>\fP
.PP
Inherits \fBList< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "iterator_type \fBpop\fP ()"
.br
.RI "\fIPop an element off the top of the stack. \fP"
.ti -1c
.RI "const iterator_type \fBpeek\fP () const "
.br
.RI "\fIPeek at the first element, but don't pop it off. \fP"
.ti -1c
.RI "void \fBpush\fP (const iterator_type &item)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBStack\fP< iterator_type > & \fBoperator>>\fP (\fBStack\fP< iterator_type > &stack, iterator_type &item)"
.br
.ti -1c
.RI "\fBStack\fP< iterator_type > & \fBoperator<<\fP (\fBStack\fP< iterator_type > &stack, const iterator_type &item)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class Stack< T >"
A FILO \fBStack\fP, what else! 
.PP
Definition at line 36 of file Stack.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > const iterator_type \fBStack\fP< T >::peek () const\fC [inline]\fP"
.PP
Peek at the first element, but don't pop it off. 
.PP
\fBTodo\fP
.RS 4
Throw an exception? 
.RE
.PP

.PP
Definition at line 65 of file Stack.h.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class T > \fBStack\fP<iterator_type>& operator<< (\fBStack\fP< iterator_type > & stack, const iterator_type & item)\fC [friend]\fP"
.PP
\fBSee also:\fP
.RS 4
push 
.RE
.PP

.PP
Definition at line 80 of file Stack.h.
.SS "template<class T > \fBStack\fP<iterator_type>& operator>> (\fBStack\fP< iterator_type > & stack, iterator_type & item)\fC [friend]\fP"
.PP
\fBSee also:\fP
.RS 4
\fBpop\fP 
.RE
.PP

.PP
Definition at line 56 of file Stack.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
