.TH "Stack.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br
\fC#include 'List.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStack< T >\fP"
.br
.RI "\fIA FILO \fBStack\fP, what else! \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_STACK_H\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_STACK_H   1"
.PP
Definition at line 24 of file Stack.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
