.TH "Stream.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stream.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'bdlib.h'\fP
.br
\fC#include 'String.h'\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <fcntl.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStream\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_STREAM_H\fP   1"
.br
.ti -1c
.RI "#define \fBSEEK_CUR\fP   1"
.br
.ti -1c
.RI "#define \fBSEEK_END\fP   2"
.br
.ti -1c
.RI "#define \fBSEEK_SET\fP   0"
.br
.ti -1c
.RI "#define \fBSTREAM_BLOCKSIZE\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStream\fP & \fBoperator<<\fP (\fBStream\fP &stream, const \fBString\fP &string)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_STREAM_H   1"
.PP
Definition at line 24 of file Stream.h.
.SS "#define SEEK_CUR   1"
.PP
Definition at line 41 of file Stream.h.
.SS "#define SEEK_END   2"
.PP
Definition at line 42 of file Stream.h.
.SS "#define SEEK_SET   0"
.PP
Definition at line 40 of file Stream.h.
.SS "#define STREAM_BLOCKSIZE   1024"
.PP
Definition at line 37 of file Stream.h.
.SH "Function Documentation"
.PP 
.SS "\fBStream\fP& operator<< (\fBStream\fP & stream, const \fBString\fP & string)\fC [inline]\fP"
.PP
Definition at line 146 of file Stream.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
