.TH "String.cpp" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
String.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'String.h'\fP
.br
\fC#include 'Array.h'\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'base64.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::istream & \fBgetline\fP (std::istream &is, \fBString\fP &string)"
.br
.ti -1c
.RI "\fBString\fP \fBnewsplit\fP (\fBString\fP &str, char delim)"
.br
.RI "\fISplits off tokens. \fP"
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBString\fP &string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::istream& getline (std::istream & is, \fBString\fP & string)"
.PP
Definition at line 135 of file String.cpp.
.SS "\fBString\fP newsplit (\fBString\fP & str, char delim)"
.PP
Splits off tokens. 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The string to split a token off of 
.br
\fIdelim\fP The delimiter to tokenize with This will modify the given string to remove the first token, which is returned. If no more tokens exist, the remaining string is returned and the string becomes ''. Future calls will return a blank \fBString\fP('') 
.RE
.PP

.PP
Definition at line 253 of file String.cpp.
.SS "std::istream& operator>> (std::istream & is, \fBString\fP & string)"
.PP
Definition at line 114 of file String.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
