.TH "test" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- Test \fBList\fP 
 
.IP "\fBMember \fBArray::Array\fP(const_pointer carray) \fP" 1c
\fBArray\fP test('Some array'); 
.PP
.PP
 
.IP "\fBMember \fBArray::Array\fP(const_pointer carray, size_t len) \fP" 1c
\fBArray\fP test('Some array'); 
.PP
.PP
 
.IP "\fBMember \fBString::String\fP(const char *cstring) \fP" 1c
\fBString\fP test('Some string'); 
.PP
.PP
 
.IP "\fBMember \fBString::String\fP(const char *cstring, size_t slen) \fP" 1c
\fBString\fP test('Some string'); 
.PP
.PP
 
.IP "\fBMember \fBString::String\fP(const char ch) \fP" 1c
\fBString\fP test('a'); 
.PP

