.TH "Thread.h" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bdlib.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThread\fP"
.br
.RI "\fIExtendable thread class. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_BD_THREAD_H\fP   1"
.br
.ti -1c
.RI "#define \fBNO_THREADS\fP   1"
.br
.ti -1c
.RI "#define \fBTHREAD_DETACHED\fP   0x2"
.br
.ti -1c
.RI "#define \fBTHREAD_STARTED\fP   0x1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef short \fBthreadHandle_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBthreadId_t\fP"
.br
.ti -1c
.RI "typedef void * \fBthreadMainRet_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static \fBthreadMainRet_t\fP \fBthreadMain\fP (void *)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _BD_THREAD_H   1"
.PP
Definition at line 24 of file Thread.h.
.SS "#define NO_THREADS   1"
.PP
Definition at line 29 of file Thread.h.
.SS "#define THREAD_DETACHED   0x2"
.PP
Definition at line 50 of file Thread.h.
.SS "#define THREAD_STARTED   0x1"
.PP
Definition at line 49 of file Thread.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef short \fBthreadHandle_t\fP"
.PP
Definition at line 42 of file Thread.h.
.SS "typedef unsigned int \fBthreadId_t\fP"
.PP
Definition at line 45 of file Thread.h.
.SS "typedef void* \fBthreadMainRet_t\fP"
.PP
Definition at line 41 of file Thread.h.
.SH "Function Documentation"
.PP 
.SS "static \fBthreadMainRet_t\fP threadMain (void *)\fC [static]\fP"
.PP
Definition at line 41 of file Thread.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
