.TH "Thread.cpp" 3 "18 Dec 2009" "Version 1.0" "BDLIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Thread.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static BDLIB_NS_BEGIN \fBthreadMainRet_t\fP \fBthreadMain\fP (void *object)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static BDLIB_NS_BEGIN \fBthreadMainRet_t\fP threadMain (void * object)\fC [static]\fP"
.PP
Definition at line 41 of file Thread.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for BDLIB from the source code.
